version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
  

  backend:
    build: ./backend
    container_name: SustainaFood-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/FoodReduceDocker
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: SustainaFood-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo-data:
