sonar.projectKey=vvebwizards_Web-Wizards-SustainaFood
sonar.organization=vvebwizards
sonar.host.url=https://sonarcloud.io

# Project sources
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js

# Optional: if you generate coverage reports
# sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info