name: Build and deploy Node.js app to Azure Web App - foodreduce-backend

on:
  push:
    branches:
      - azure
    paths:
      - 'backend/**'
      - '.github/workflows/azure_foodreduce-backend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3AE0F3E38A434633873D4D658100D838 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBDD1E233D234E16ADE3A027768FECD2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8501622DEA444CD8885BF4C87A33DD9C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'foodreduce-backend'
          slot-name: 'Production'
          package: ./backend
